services:
  reverse-proxy:
    image: traefik:2.5
    command: --api.insecure=true --providers.docker=true --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#  mongodb_seed:
#    image: bitnami/mongodb:4.2
#    volumes:
#      - "./seed_db/seed:/seed"
#      - "./seed_db/mongo_import.sh:/mnt/mongo_import.sh"
#    command: 
#      - "sh"
#      - "-c"
#      - "chmod u+x /mnt/mongo_import.sh && /mnt/mongo_import.sh"
#    user: "1000:1000"
#    depends_on:
#      - mongodb
    #restart: on-failure
#    tty: true
  mongodb:
    image: bitnami/mongodb:4.2
    ports:        # port does not need to be exported in production env but good for debug...
      - "27017:27017"
    volumes:
 #     - "mongodb_data:/bitnami"
      - "/srv/mongodb:/bitnami/mongodb"
  catamel:
    image: dacat/catamel:latest
    depends_on:
      - mongodb
    volumes:
      - ./config/catamel/config.local.js:/home/node/app/server/config.local.js
    #   - ./config/catamel/providers.json:/home/node/app/server/providers.json
    labels:
      - "traefik.http.routers.catamel.rule=PathPrefix(`/api`, `/auth`, `/explorer`)"
      - "traefik.http.routers.catamel.entrypoints=web"
  catanie:
    build:
      #context: https://github.com/SciCatProject/frontend.git#develop
      context: https://github.com/SciCatProject/frontend.git#d3d788238ec5f18f6787b1ba2a4b26b0e9ef34f7
    depends_on:
      - catamel
    labels:
      - "traefik.http.routers.catanie.rule=PathPrefix(`/`)"
      - "traefik.http.routers.catanie.entrypoints=web"
    volumes:
      - ./config/catanie/environment.ts:/usr/src/app/src/environments/environment.development.ts
  search-api:
    image: dacat/panosc-search-api:latest
    depends_on: 
      - catamel
    labels:
      - "traefik.http.routers.panosc-search-api.rule=PathPrefix(`/panosc-api`, `/panosc-explorer`)"
      - "traefik.http.routers.panosc-search-api.entrypoints=web"
    environment:
      BASE_URL: "http://catamel:3000/api/v3"
      FACILITY: "SAMPLE-SITE"
#volumes:
#  mongodb_data:
#    driver: local
